### ISSUE TITLE
How is the contract used by the scripts?

### ISSUE THREAD

**Issue by bhchiang** [jamiew/ohmfork-autoclaim#1]
There's a copy of the minting contract in the repository: https://github.com/jamiew/snowbankdao-autoclaim/blob/main/contracts/TimeBondDepository.sol. But I briefly checked the scripts and couldn't see how the contract is being used. Why is the contract there?

**Comment by jamiew** [comment]
lazy man's ABI

it is invokved like so

```
  const contract: Contract = await ethers.getContractAt(contractName, contractAddress)
  ```

see `contract.ts` to see that `contractName = TimeBondDepository`

gonna close this issue but lmk if any other questions!

**Comment by bhchiang** [comment]
Thanks for clarifying! I'm new to AVAX so I'm a bit confused because it seems like the contractAddress is also present. Why don't we just retrieve the contract ABI from the AVAX chain using the contractAddress?

**Comment by jamiew** [comment]
would love that, but I am not aware of any methods to retrieve an ABI directly from the blockchain. do you mean retrieving it from e.g. whatever the AVAX equivalent of Etherscan is? I forget the name offhand

Opened up #3 to help clean this up!
